version: '2.2'

services:
  redis-master:
    image: 'redis:6'
    container_name: redis_master
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    # command: redis-server --port 6379
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=1234
    volumes:
      - ./rdcli/log:/var/log/redis/redis-server.log
      - /redis_data/redis_main:/data
      - ./rdcli/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-network
  # redis-replica:
  #   image: 'redis:6'
  #   container_name: redis_slave
  #   command: redis-server --slaveof redis-master 6379 --port 6380 --slave-announce-ip redis-master
  #   ports:
  #     - '6380:6380'
  #   depends_on:
  #      - redis-master
  #   volumes:
  #     - /redis_data/redis_replication:/data
  #   environment:
  #     - REDIS_REPLICATION_MODE=slave
  #     - REDIS_MASTER_HOST=redis-master
  #     - REDIS_MASTER_PORT_NUMBER=6379
  #     - REDIS_MASTER_PASSWORD=1234
  #     - REDIS_PASSWORD=123
  #   networks:
  #     - redis-network
volumes:
  redis_data:
    name: redis-vl
    driver: local
    external: true
networks:
 redis-network:
    driver: bridge