version: '2.2'
services:
  backend:
    build:
      context: "./"
      dockerfile: "./Dockerfile"
      cache_from:
        - ubuntu:16.04
        - golang:1.13.1 
    depends_on:
      - redis-master
    image: qc-monitor:v1.0.0
    volumes:
      - ./storage:/app/storage
    ports:
      - "8686:8686"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ping"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks:
     - redis-network
  redis-master:
    image: 'redis:6'
    container_name: redis_master
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    # command: redis-server --port 6379
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=1234
    volumes:
      - ./rdcli/log:/var/log/redis/redis-server.log
      - /redis_data/redis_main:/data
      - ./rdcli/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-network
  # redis-replica:
  #   image: 'redis:6'
  #   container_name: redis_slave
  #   command: redis-server --slaveof redis-master 6379 --port 6380 --slave-announce-ip redis-master
  #   ports:
  #     - '6380:6380'
  #   depends_on:
  #      - redis-master
  #   volumes:
  #     - /redis_data/redis_replication:/data
  #   environment:
  #     - REDIS_REPLICATION_MODE=slave
  #     - REDIS_MASTER_HOST=redis-master
  #     - REDIS_MASTER_PORT_NUMBER=6379
  #     - REDIS_MASTER_PASSWORD=1234
  #     - REDIS_PASSWORD=123
  #   networks:
  #     - redis-network
volumes:
  redis_data:
    name: redis-vl
    driver: local
    external: true
networks:
 redis-network:
    driver: bridge